ARG BASE_IMAGE=mmct_base:latest
FROM ${BASE_IMAGE}

# Set working directory
WORKDIR /app

# Copy .env file
COPY mmct/ mmct/
COPY config/ config/
# COPY docs/ docs/
COPY mcp_server/ mcp_server/
COPY .env .

RUN pip install -e .

# Expose the MCP server port
EXPOSE 8000

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Run the MCP server
CMD ["python", "mcp_server/main.py"]
