"""Pipeline runner for orchestrating step execution.

This module provides the core orchestration logic for executing sequential 
ingestion steps, tracking their results, and generating execution reports.
"""

import time
import json
import os
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

from .steps.base import StepContext, StepResult
from .config.schemas import PipelineConfig
from .steps.registry import get_step_class


@dataclass
class StepExecutionRecord:
    """Record of a single step's execution within a pipeline.

    Attributes:
        step_id (str): The unique identifier for the step.
        step_type (str): The class name or type identifier of the step.
        status (str): The outcome of the step ("completed", "failed", "skipped").
        duration_seconds (float): Time taken to execute the step.
        metrics (Dict[str, float]): Performance or quantitative data from the step.
        artifacts (List[str]): Paths to files generated by the step.
        error (str, optional): The error message if the step failed.
    """

    step_id: str
    step_type: str
    status: str
    duration_seconds: float
    metrics: Dict[str, float] = field(default_factory=dict)
    artifacts: List[str] = field(default_factory=list)
    error: Optional[str] = None


@dataclass
class PipelineReport:
    """Consolidated report of a pipeline's execution.

    Attributes:
        pipeline_name (str): The name of the executed pipeline.
        total_duration_seconds (float): Total time for all steps to finish.
        status (str): Overall status ("completed", "failed", "partial").
        steps (List[StepExecutionRecord]): Individual records for each step.
    """

    pipeline_name: str
    total_duration_seconds: float
    status: str
    steps: List[StepExecutionRecord] = field(default_factory=list)

    def summary(self) -> str:
        """Generates a human-readable summary of the pipeline execution.

        Returns:
            str: A formatted summary string.
        """
        completed = sum(1 for s in self.steps if s.status == "completed")
        failed = sum(1 for s in self.steps if s.status == "failed")

        return (
            f"Pipeline '{self.pipeline_name}' {self.status}\n"
            f"  Duration: {self.total_duration_seconds:.2f}s\n"
            f"  Steps: {completed} completed, {failed} failed, {len(self.steps)} total"
        )

    def save(self, output_path: str) -> None:
        """Saves the pipeline report to a JSON file.

        Args:
            output_path: The local filesystem path where the JSON should be saved.
        """
        with open(output_path, "w") as f:
            json.dump(asdict(self), f, indent=2)


class PipelineRunner:
    """Orchestrator for sequential execution of video ingestion steps.

    The PipelineRunner iterates through a configured list of steps, 
    instantiating them from the registry and executing them within a 
    shared context. It handles error propagation and result aggregation.

    Attributes:
        pipeline_config (PipelineConfig): The configuration defining the steps.
        context (StepContext): The shared state and providers for all steps.
        logger (Any): Logger instance for tracking progress.
        execution_records (List[StepExecutionRecord]): Accumulated step results.
    """

    def __init__(
        self,
        pipeline_config: PipelineConfig,
        context: StepContext,
    ):
        """Initializes the PipelineRunner.

        Args:
            pipeline_config: Pipeline configuration with steps to execute.
            context: Shared context (providers, state) for all steps.
        """
        self.pipeline_config = pipeline_config
        self.context = context
        self.logger = context.logger
        self.execution_records: List[StepExecutionRecord] = []

    async def run(self) -> PipelineReport:
        """Executes the pipeline steps in sequence.

        Wraps execution with progress tracking (tqdm) if verbosity is low. 
        Updates the data store with outputs from each successful step.

        Returns:
            PipelineReport: The complete report of the pipeline's execution.

        Raises:
            Exception: Re-raises any error encountered during step execution.
        """
        pipeline_start = time.time()
        pipeline_status = "completed"

        if self.context.verbosity >= 1:
            self.logger.info(f"Starting pipeline: {self.pipeline_config.name}")
            self.logger.info(f"Mode: {self.pipeline_config.mode}")
            self.logger.info(f"Steps: {len(self.pipeline_config.steps)}")

        try:
            steps_iterable = self.pipeline_config.steps

            # If verbosity is 0, wrap with tqdm for a clean progress bar
            if self.context.verbosity == 0:
                from tqdm import tqdm

                steps_iterable = tqdm(
                    self.pipeline_config.steps,
                    desc=f"Ingesting {self.context.video_id[:8]}...",
                    unit="step",
                )

            for idx, step_cfg in enumerate(steps_iterable, 1):

                if self.context.verbosity >= 1:
                    self.logger.info(
                        f"[{idx}/{len(self.pipeline_config.steps)}] Executing step: {step_cfg.id} ({step_cfg.type})"
                    )
                elif self.context.verbosity == 0:
                    if hasattr(steps_iterable, "set_description"):
                        steps_iterable.set_description(f"Step: {step_cfg.id}")

                try:
                    # Get step class from registry and instantiate
                    StepClass = get_step_class(step_cfg.type)
                    step = StepClass(step_id=step_cfg.id, params=step_cfg.params)

                    # Execute step logic
                    step_start = time.time()
                    result = await step.run(self.context)
                    step_duration = time.time() - step_start

                    # Store outputs in centralized data store for subsequent steps
                    for key, value in result.outputs.items():
                        self.context.data_store.set(step_cfg.id, key, value)

                    # Accumulate execution record
                    record = StepExecutionRecord(
                        step_id=step_cfg.id,
                        step_type=step_cfg.type,
                        status="completed",
                        duration_seconds=step_duration,
                        metrics=result.metrics,
                        artifacts=result.artifacts,
                    )
                    self.execution_records.append(record)

                    if self.context.verbosity >= 1:
                        self.logger.info(f"Step {step_cfg.id} completed in {step_duration:.2f}s")

                    # Handle explicit termination requests from a step
                    should_continue = result.outputs.get("should_continue", True)
                    if not should_continue:
                        msg = f"Step {step_cfg.id} requested pipeline termination. Skipping remaining steps."
                        if self.context.verbosity >= 1:
                            self.logger.info(msg)
                        pipeline_status = "completed"
                        break

                except Exception as e:
                    step_duration = time.time() - step_start if "step_start" in locals() else 0.0
                    self.logger.exception(f"Step {step_cfg.id} failed: {e}")

                    record = StepExecutionRecord(
                        step_id=step_cfg.id,
                        step_type=step_cfg.type,
                        status="failed",
                        duration_seconds=step_duration,
                        error=str(e),
                    )
                    self.execution_records.append(record)
                    pipeline_status = "failed"
                    raise

        except Exception as e:
            if self.context.verbosity >= 1:
                self.logger.exception(f"Pipeline {self.pipeline_config.name} failed: {e}")
            pipeline_status = "failed"
            raise

        finally:
            # Finalize report even on failure
            total_duration = time.time() - pipeline_start

            report = PipelineReport(
                pipeline_name=self.pipeline_config.name,
                total_duration_seconds=total_duration,
                status=pipeline_status,
                steps=self.execution_records,
            )

            self.logger.info(report.summary())

            # Persist report if output directory and saving are enabled
            if self.context.output_dir and self.context.save_local_report:
                report_path = os.path.join(
                    self.context.output_dir,
                    f"{self.context.video_id}_ip_report.json",
                )
                report.save(report_path)
                self.logger.info(f"Pipeline report saved to: {report_path}")
            elif not self.context.save_local_report:
                self.logger.info("Report saving disabled by configuration.")

        return report
