# app/Dockerfile.app
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

# Copy only what's needed for the main service
COPY . .
# If there are more submodules, add them here

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]